name: Create LeetCode Daily Problem Issue

on:
  workflow_dispatch:
  schedule:
    - cron: "7 0 * * *"  # Runs daily at 00:07 UTC

jobs:
  create-daily-lc-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Change this to match your script's requirements

      - name: Install dependencies
        run: |
          pip install -U requests python-dotenv

      - name: Run the script
        run: python lc_gh_issue_bot.py