name: Create LeetCode Daily Problem Issue

on:
  workflow_dispatch:
  schedule:
    - cron: "7 0 * * *"  # Runs daily at 00:07 UTC

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Daily Leetcode Issue Creator
        uses: cin-kay/leetcode-daily-issue-action@v1.0.0
